<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FDD7CCMN" failures="3" tests="3" name="Test(failed)" time="24.427" errors="0" timestamp="2025-08-26T14:34:25 IST">
  <testcase classname="testCases.TC_003LoginDDT" name="verifyloginDDT" time="11.551">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003LoginDDT.verifyloginDDT(TC_003LoginDDT.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginDDT -->
  <testcase classname="testCases.TC_003LoginDDT" name="verifyloginDDT" time="4.262">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003LoginDDT.verifyloginDDT(TC_003LoginDDT.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginDDT -->
  <testcase classname="testCases.TC_003LoginDDT" name="verifyloginDDT" time="1.926">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_003LoginDDT.verifyloginDDT(TC_003LoginDDT.java:65)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginDDT -->
</testsuite> <!-- Test(failed) -->
